# Generated by Django 4.0.1 on 2022-02-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_alter_client_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
